# Generated by Django 5.1.4 on 2025-01-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sn', '0002_portfolio_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('name', models.CharField(default='name', max_length=50)),
                ('org', models.CharField(default='org', max_length=50)),
            ],
        ),
    ]
