# Generated by Django 5.1.4 on 2025-01-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sn', '0003_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='addr',
            field=models.CharField(default='Bhagalpur, Bihar, India', max_length=200),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.CharField(default='snk.22104@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='numb',
            field=models.CharField(default='+91 000-000-0000', max_length=20),
        ),
    ]
