# Generated by Django 5.1.4 on 2025-01-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sn', '0004_about_addr_about_email_about_numb'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='fav',
            field=models.ImageField(default='../static/img/favicon.png', upload_to='icons/'),
        ),
    ]
